### ISSUE TITLE
1.7.0 release checklist

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#158]
A list of things we should try to have in place for 1.7.0; we can release RC's in the meantime.  Note that not all of these are blockers but would be good to have in place.

- [x] #87 Significant issue with versioning
- [x] Update version
- [x] Update CHANGES, #164 
- [x] Review network tests, #160 
- [x] Review branch diffs for v1.6.x and master, make sure no commits are in v1.6.x only; see #110 for an example; bug tracked in #161 
- [x] Review INSTALL, INSTALL.WIN docs #165
- [x] #166 (fairly major one)
- [x] #151 
- [x] #155 
- [x] #163
- [x] #146 (look into, may not be a blocker)
- [x] Set up other split-out modules up for release (each with a v1.7.0 starting version) - will make these separate items (release is not dependent on this)
- [x] #153 (this may not be a true bug)

**Comment by cjfields** [comment]
Version updated

**Comment by cjfields** [comment]
Will bump #146 for the next release, not sure if it's an actual bug.  Setting up final RC.
